name: Sonar Test

on: workflow_dispatch

jobs:
  unit_tests:
    name: Unit Tests

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DESTINATION_BRANCH: "${{ github.base_ref }}"
      PULL_REQUEST_NUMBER: "${{ github.event.number }}"
      SOURCE_BRANCH: "${{ github.head_ref }}"
      SONARCLOUD_URL: sonarcloud.io      

    steps:
      # Checkout this commit
    - name: Checkout Branch
      uses: actions/checkout@v2
      with:
        repository: constellation-app/constellation
        path: constellation
      
      # Cache the ivy dependencies
    - name: Restore Ivy Cache
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: ~/.ivy2
        key: ${{ runner.os }}-ivy-${{ hashFiles('constellation/CoreDependencies/src/ivy.xml') }}

    - name: Create Ivy Cache
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        mkdir ~/.ivy2

    - name: Add Execute Privilege to Scripts
      run: |
        chmod +x constellation/.githubutilities/sonar.sh

    - name: Run Sonar
      uses: addnab/docker-run-action@v3
      with:
        image: constellationapplication/netbeans-runner:12.0.4
        options: |
          --volume ${{ github.workspace }}:/code
          --workdir /code/constellation
        run: |
          echo .githubutilities/sonar.sh "${GITHUB_REPOSITORY}" "${PULL_REQUEST_NUMBER}" "${DESTINATION_BRANCH}" "${SOURCE_BRANCH}" "${SONAR_TOKEN}"
