name: Test

on: workflow_dispatch
 
jobs:
  create-release-build:
    runs-on: ubuntu-latest
    env:
      RUNNER_IMAGE: "constellationapplication/netbeans-runner:12.0.4"
      CYBER_VERSION: "v1.6.0"
    steps:
      - name: Update GH Actions Tools 
        run: |
          apt-get update
          apt-get install bash docker git sed
      - name: Create Workspace Dir for operations
        run: |
              mkdir -p ./workspace
      - name: Checkout Constellation repository
        uses: actions/checkout@v2
        with:
          repository: constellation-app/constellation
          path: ./workspace/constellation
      - name: Checkout Constellation Cyber repository
        uses: actions/checkout@v2
        with:
          repository: AustralianCyberSecurityCentre/constellation_cyber_plugins
          path: ./workspace/constellation_cyber_plugins
      - name: Checkout Constellation Applications repository
        uses: actions/checkout@v2
        with:
          repository: constellation-app/constellation-applications
          path: ./workspace/constellation-applications
      - name: Update Version Number
        run: |
               sed -i "s/(under development)/$CYBER_VERSION/" ./workspace/constellation/CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/startup/Startup.java
               sed 's/"Constellation";/"Constellation Cyber";/' ./workspace/constellation/CoreUtilities/src/au/gov/asd/tac/constellation/utilities/BrandingUtilities.java
      - name: Add Execute Privilege to Scripts
        run: |
              chmod +x ./workspace/constellation-applications/build-zip.sh
              chmod +x ./workspace/constellation-applications/functions.sh
              echo $(pwd)
              ls
      - name: Run build process within Docker container
        run: |
            echo docker pull "${RUNNER_IMAGE}"
            echo docker run -e GIT_DISCOVERY_ACROSS_FILESYSTEM=1 \
            --mount "type=bind,source=$(pwd),target=/code" \
            --workdir /code/workspace/constellation-applications \
            ${RUNNER_IMAGE} \
            ./build-zip.sh -a constellation-cyber -m "constellation constellation-adaptors constellation_cyber_plugins"
